### ISSUE TITLE
Implement 3-point Abel inversion technique

### ISSUE THREAD

**Issue by DhrubajyotiDas** [PyAbel/PyAbel#61] opened 2015-12-28 23:00 UTC
[Dasch, 1992](https://www.osapublishing.org/ao/abstract.cfm?uri=ao-31-8-1146) (Applied Optics, Vol 31, No 8, March 1992, Pg 1146-1152) discusses several numerical techniques for performing Abel inversions of cylindrically symmetric line-of-sight images to extract the underlying radial distributions (see discussion in #56). One technique discussed in the paper is the 'Abel inversion using three-point interpolation' or '3-pt Abel' technique; this technique is fairly popular in the combustion diagnostics literature. 

It would be useful to incorporate this technique in PyAbel. 

(more details coming in 2016!)

**Comment by DanHickstein** [comment] 2015-12-30 18:38
Awesome! I'm excited to see how this method works!

**Comment by DhrubajyotiDas** [comment] 2016-01-01 23:11
Happy New Year!

Prof. Marshall Long's group at Yale uses [the linked matlab script](https://gist.github.com/DhrubajyotiDas/16d9381a78352f93bdfe) to implement the 3-point Abel deconvolution as per Dasch 1992.

[I've ported this to python](https://gist.github.com/DhrubajyotiDas/0159ccbc075821632e8c) and run some basic tests. This inversion is fairly quick and works on a half-image. As usual, the raw data must have cylindrical symmetry, and the output rows are independent (transform works on a row-by-row basis).

![dashc 3pt abel](https://cloud.githubusercontent.com/assets/6530840/12072553/dfbdbec8-b0b1-11e5-8e84-410800c3417a.png)

Future works include:
* Timed runs
* Tests with noisy raw data
* Tests with experimental raw data
* Comparison to BASEX and other approaches

I have not filed a PR for this because I'd like @DanHickstein, @rth, and @stggh's input on how to package this inversion with the proper wrapper functions, etc.

**Comment by stggh** [comment] 2016-01-02 00:32
@DhrubajyotiDas this algorithm is pretty neat.  Thanks, for taking the time to make it available. 

I have only skimmed through your code and the associated paper. It indicates that  D is an upper triangular matrix, apart from an additional diagonal ```j=i-1```, and the special case (```i=0,j=1```). Hence, you need only evaluate ~ upper triangle, so ```range(i-1,col)``` may be sufficient for the loop on line 25, and the tests for ```j<i-1``` may be excluded in the ```OP_``` functions. These may also be written as vector functions. I think that the ```F[j] += D[j,k] * P[k]``` calculation may be written as a matrix (or dot) multiplication. In the end it will be very compact code. I will investigate if I find some free time.

One minor typo in ```iable_dasch...```

**Comment by DhrubajyotiDas** [comment] 2016-01-02 19:12
@stggh Thanks for the comments! I haven't looked at the algorithm in great detail, so I cannot take any credit for the above code. It's mostly a one-to-one port from the Long group's Matlab code, aimed at getting the discussion started here. I do believe that `F[j] += D[j,k] * P[k]` could be vectorized in a straightforward fashion.

**Comment by DanHickstein** [comment] 2016-01-03 05:54
@DhrubajyotiDas, great work! Very exciting!

As far as packaging goes, our current system is that your file should be called ``abel/<method>.py``, where ``method`` is the name of your transform. I think that it would be good practice to call each method by something that describes the technique, for example, would it make sense to refer to this method as ``three_point`` rather than ``dasch``?

Then, I think that the main requirement is that you provide a function called ``iabel_three_point()``, which takes a full image as an argument (you'll need to split the image in half and feed both halves to your algorithm and then stitch them back together). The new plan is to keep the ``calc_speeds`` function out of the individual transform functions, so don't worry about incorporating this for now. If the algorithm can also perform a forward transform, then a similar function ``fabel_three_point()`` should be used. The standard practice has been to have the ``iabel_(method)`` function perform the preliminary image manipulations, load basis sets, etc., and rely on a sub-function ``iabel_(method)_transform()`` to do the actual math. But this is just a convention to separate the real math from the other stuff. 

You should also write a test that checks the functionality of your transform. Perhaps you can perform a transform on a Gaussian function and check this against the analytical transform. 

In addition, you should provide an example showing the use of your transform.

@rth can let us know if I forgot anything. :)

**Comment by rth** [comment] 2016-01-05 10:38
@DhrubajyotiDas This is very nice!

It would have been tempting to call it `iabel_3point`, but the problem is that `3point.py` is not a valid module name. So I guess we'll have to go with `iabel_three_point`. I agree with @DanHickstein that `dasch` would be confusing, as that paper also mentions 2-point Abel etc. 

I'll make a separate comment with respect to the `iabel_<method>_transform` vs  `iabel_<method>` use and about ,stitching together the left and right side as it is also relevant for other implementations. 

Regarding code optimisation, as @stggh mentioned replacing the `F[j] += D[j,k] * P[k]`  loop, by a dot product would be both more readable and faster. Also not sure if that would help speed wise, but the creation of the trigonal matix can be vectorised, defining `i`,`j` with `i, j = np.meshgrid(... )` and then working with arrays of indices:   

     def OP1(i,j):
         I1 = np.zeros(i.shape)
         mask = j < i
         I1[mask] = 0
         mask = j == i
         im, jm = i[mask], j[mask]
         I1[mask] = ((2*jm+1)**2 - 4*im**2)**0.5/(2*np.pi) - 2*j*OP0(im,jm)
         mask = j > i
         im, jm = i[mask], j[mask]
         I1[mask] = (((2*jm+1)**2 - 4*im**2)**0.5 - ((2*jm-1)**2 - 4*im**2)*  *0.5)/(2*np.pi) - 2*j*OP0(im,jm)
         return I1

Although, not sure if this is really necessary. As long as  it gives right results, maybe  we just merge the one-to-one Matlab port at first with a few unit tests, then if somebody wants to optimize it further they could....

**Comment by DhrubajyotiDas** [comment] 2016-01-09 01:59
Regarding the speed optimization issue:

I realized that the `D` matrix being calculated (the triangular matrix that is multiplied to the raw image) is independent of the `raw_data` provided by the user, and is only dependent on the size of the image (`D` is a square matrix of dimensions `col x col` where `col` is the number of columns in `raw_data`). This means we can reuse `D` if the user is batch processing images of the same size, which should speed up the processing. 
 
In the latest commit of #64, I've enabled the ability to cache this `D` matrix, similar to the code we use to cache the basis sets in BASEX.

I'll also be looking at @rth's (awesome, as always) vectorized loops to speed things up more.

**Comment by rth** [comment] 2016-01-12 21:21
Closing this as the corresponding PR #64 was merged. Possible future optimizations could be addressed in a separate PR.

**Closed by rth** 2016-01-12 21:21 UTC
Labels: enhancement

**Comment by DhrubajyotiDas** [comment] 2016-01-12 21:23
Thanks for the comments, everyone!

**Comment by DanHickstein** [comment] 2016-01-12 21:28
Thanks @DhrubajyotiDas!

**Comment by Seonggun** [comment] 2017-02-27 16:34
Hi all,

Thanks for sharing. 

In the line 7 (-2*j*OP0(i,j)) and 9 (-2*j*OP0(i,j)), the sign is different with the Dasch, 1992 (Applied Optics, Vol 31, No 8, March 1992, Pg 1146-1152). 

In the paper, it was positive sign.  

```

1.         function I1 = OP1(i,j)
2.             % Define operator OP1
3.             
4.             if j<i
5.                 I1 = 0;
6.             elseif j==i
7.                 I1 = ((2*j+1)^2-4*i^2)^0.5/(2*PI)-2*j*OP0(i,j);
8.             elseif j>i
9.                 I1 = (((2*j+1)^2-4*i^2)^0.5-((2*j-1)^2-4*i^2)^0.5)/(2*PI)-2*j*OP0(i,j);
10.             end

```

**Comment by DanHickstein** [comment] 2017-02-27 16:41
Hi @Seonggun! 

Thanks for bringing this to our attention. To keep us organized, could you please open a New Issue here: https://github.com/PyAbel/PyAbel/issues

I would say that you may have spotted a bug, but I believe that we have benchmarked the three-point transform against other transform methods, and seen similar results. So, perhaps there is some reason that the sign flipped. If I recall correctly, @DhrubajyotiDas said that he fixed a few typos...

**Comment by DhrubajyotiDas** [comment] 2017-02-27 16:50
Thanks @Seonggun. As @DanHickstein mentioned, the original paper had several unfortunate typos in it, and this is most likely one of them. I don't have access to Dasch's errata at the moment, but these errors have been noted and corrected here https://www.lib.utexas.edu/etd/d/2002/martinkm07836/martinkm07836.pdf

Specifically, see pages 114 and 115 of the document linked above.

**Comment by Seonggun** [comment] 2017-02-27 16:56
Hi, Thanks! @DhrubajyotiDas, also for sharing the book.
 
I just tested the code, they should be 'negative'.

**Comment by DanHickstein** [comment] 2017-02-27 16:59
@DhrubajyotiDas beat me to it. I was just about to link that thesis. 

There is some discussion of this here: https://github.com/PyAbel/PyAbel/pull/64#issuecomment-169831494

On page 170 (page 188 of the PDF file), there is this list:

![image](https://cloud.githubusercontent.com/assets/1107796/23370269/677ebca6-fcd1-11e6-87cc-996293ca592a.png)

In the Dasch.py, we do have a comment on [line 180 ](https://github.com/PyAbel/PyAbel/blob/master/abel/dasch.py#L180) to indicate that we are correcting a typo. Perhaps, at the top of Dasch.py, we should also include something to the effect of: "Please note, some of the equations in the 1992 paper by Dasch contained typos. These have been corrected, as described in the 2002 PhD thesis of Karl Martin. See pages 114, 115, and 170: https://www.lib.utexas.edu/etd/d/2002/martinkm07836/martinkm07836.pdf"

**Comment by DanHickstein** [comment] 2017-02-27 17:01
Thanks for testing this @Seonggun!

Out of curiosity, what application are you using PyAbel for? And please let us know if you have any more suggestions or questions!

**Comment by Seonggun** [comment] 2017-02-27 17:11
Thanks @DanHickstein !

I am doing quite similar with the Karl Martin's work. Applying three-points-Abel inversion to reconstruct soot volumetric fraction in the flame and OH* as well. 

This code is much faster than the one I used, Fourier-based Abel inversion. See the reference, G. Pretzler, Z. Naturforsch. 46a, 639 (1991).

**Comment by DanHickstein** [comment] 2017-02-27 17:24
Very interesting! @DhrubajyotiDas also works with flame analysis.

I have been very impressed with the Dasch algorithms (two-point, three-point, onion-peeling) for the inverse Abel transform. I think that they are currently the fastest algorithms though this is somewhat computer-dependent, and the Hansen-Law method is likely faster for larger images.

What kind of code were you using for the Fourier-based Abel inversion? We are always looking to add more options for Abel transforms to PyAbel. Even if they are not the fastest, they might be ideal for some specific applications. If you already have matlab/python code, it might be easy to incorporate.

**Comment by Seonggun** [comment] 2017-02-27 18:00
Hi, 

Here is the code,https://se.mathworks.com/matlabcentral/fileexchange/43639-abel-inversion-algorithm. 
I have tested this code, it works quite well, but it is very time consuming. 

I made a comparison between two methods. 

![comparison](https://cloud.githubusercontent.com/assets/26067529/23373145/f26a20ec-fd1e-11e6-99e2-ad9bd26c0caf.png)

**Comment by DhrubajyotiDas** [comment] 2017-02-27 19:34
@Seonggun glad to have another flame person in the mix.

Looking at the comparison between the Fourier and 3-pt, the thing that strikes me the most is the Fourier trace seems to be smoother near the centerline than the 3-pt. Is this something you have observed elsewhere or just a random coincidence? The reason I ask is because we are always interested in algorithms that are not as prone to noise near the symmetry axis (an unfortunate reality for many inversion algorithms).

**Comment by DanHickstein** [comment] 2017-02-27 19:37
Good point @DhrubajyotiDas. We have spent a lot of time benchmarking the speed of the various algorithms, but we haven't spent enough time looking at the quality. Have you determined which algorithms are must susceptible to centerline noise? Also, isn't most of the centerline noise caused by high-frequency noise in your image? Could you just low-pass filter before transforming?

**Comment by DhrubajyotiDas** [comment] 2017-02-27 19:55
> Have you determined which algorithms are must susceptible to centerline noise?

I have not, but this could be a new project. We'd have to define standardized images with standardized amounts of noise, etc., and possibly construct a speed-noise tradeoff, if such a pareto frontier exists. 

>Also, isn't most of the centerline noise caused by high-frequency noise in your image? Could you just low-pass filter before transforming?

I have used low pass filtering, typically as Gaussian blur filters, to help with the noise issue. A pre-transform low-pass filter on the raw data combined with a Savitzky-Golay filter on the transformed data usually works out really well. Unfortunately, with my post-transform treatment of the inverted data, I usually end up amplifying the centerline noise, so I have to resort to aggressive median filtering in the centerline neighborhood as well. If the transform algorithm itself were better behaved, a lot of this could possibly be avoided.

**Comment by DhrubajyotiDas** [comment] 2017-02-27 19:58
@DanHickstein (as an aside), I'm still looking into acquiring raw data in video form to test real-time PyAbel inversion applications - had to order in new hardware, since my previous arrangement wasn't working out.

**Comment by Seonggun** [comment] 2017-02-27 20:50
Glad to talk with you all. I have tried median filtering, with [7 7]. 
I will upload two images. First one is based on three points, another one is Fourier based. They look quite similar. 
![550c_
![550c_60bar_800bar_oh_ave_15_vf_norm_111](https://cloud.githubusercontent.com/assets/26067529/23379306/c20b64c0-fd36-11e6-880a-f6dec3f022e5.png)
60bar_800bar_oh_ave_15_abel_threepoints_111](https://cloud.githubusercontent.com/assets/26067529/23379296/bb74be04-fd36-11e6-9885-91a87b99dd24.png)

**Comment by stggh** [comment] 2017-02-27 21:21
Hello @Seonggun, welcome.   

> spent enough time looking at the quality.

I think that `examples/example_all_O2.py` makes a pretty good comparison. There is not much between the algorithms in terms of noise propagation, apart from `linbasex`, which may simply require a parameter tweak.

![example_all_o2](https://cloud.githubusercontent.com/assets/10932229/23380370/9f4fff74-fd8e-11e6-8818-82b5ce96eb22.png)

> Fourier trace seems to be smoother near the centerline than the 3-pt

Have you applied the Jacobian or played with `dr`?

**Comment by Seonggun** [comment] 2017-02-28 09:40
Hi all, 
Thanks everyone for the input so far. It's been great to discuss with you all. 

Shortly summery: page 121-122, it was discussed in the 2002 PhD thesis of Karl Martin that the sensitivity of the flame center and the need of smoothing the data before deconvoluting the data. I have been also trying different center (moving one or two pixels), it was very sensitive to the value of the center. Either before smoothing the data (image in my case) or applying the median filter after reconstruction of image, there was no big difference.  

For me, I am processing massive images, therefore, three points would be the most appropriate method for me, it is cheap and fast.  

@stggh , thank you for the example. I haven't tried the Jacobian or played with dr, but I think I will skip this part.

**Comment by DanHickstein** [comment] 2017-02-28 15:31
@Seonggun: Good to discuss this with you as well!

You may have noticed that PyAbel does have some methods to try to find the center (with sub-pixel precision) automatically: https://pyabel.readthedocs.io/en/latest/abel.html#module-abel.tools.center  

Of course, you may have better luck finding the center yourself. For one of my datasets, I tried looped through many different centers, saved each image, opened them all as a "Stack" in [ImageJ](https://imagej.nih.gov/ij/) and scrolled through the "movie" until I decided which one looked the best.

How massive are your images? You could consider downsampling. For the truly huge images, I think that we found that the Hansen-Law transform was somewhat faster than three-point.

**Comment by DanHickstein** [comment] 2017-02-28 15:33
> @DanHickstein (as an aside), I'm still looking into acquiring raw data in video form to test real-time PyAbel inversion applications - had to order in new hardware, since my previous arrangement wasn't working out.

@DhrubajyotiDas, This is super exciting! I can't wait to see it in action. Let us know if we can help in some way.

**Comment by stggh** [comment] 2017-02-28 21:51
>  I think that we found that the Hansen-Law transform was somewhat faster than three-point.

Time to pull out @DanHickstein's [pyabel_benchmark_plot.py](https://gist.github.com/DanHickstein/9b985b903f9062831f40) code:

![pyabel-benchmarks](https://cloud.githubusercontent.com/assets/10932229/23435402/8da80924-fe5b-11e6-8220-c46eb48e1e20.png)

The `dasch` methods win all the way. `hansenlaw` starts to overtake `basex` `n>1200` **but** that does not include time taken for the initial basis calculation. YMMV

Run on a Dell OptiPlex 7040, Ubuntu 16.10, Anaconda Python 3.5.2:
```
 lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 94
Model name:            Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
Stepping:              3
CPU MHz:               1961.059
CPU max MHz:           4000.0000
CPU min MHz:           800.0000
BogoMIPS:              6816.00
Virtualisation:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              8192K
NUMA node0 CPU(s):     0-7
```

**Comment by stggh** [comment] 2017-03-03 00:53
Note I am not familiar with flame image analysis.

@Seonggun the image you supplied may have already been inverse Abel transformed(?):
![flameplot](https://cloud.githubusercontent.com/assets/10932229/23533523/660fb932-0006-11e7-882a-0ff291a3bdbb.png)

In any case the results are similar to what you have [found.](https://github.com/PyAbel/PyAbel/issues/61#issuecomment-282798634) The positive rise near the image centre is, I believe, due to an overcorrection of the image background, so perhaps, there is some missing intensity near the image centre in your data.

The `PyAbel` codes are tested against functions with known Abel transforms, see `abel/tests/test_dasch_methods.py` so I think that there should be no issue with any Jacobian scaling.

Code for the plot, in case of interest:

```python
import numpy as np
import abel
import matplotlib.pyplot as plt
from scipy.misc import imread


flame = imread("flame.png", flatten=True)

Tf = abel.Transform(flame, method='three_point', symmetry_axis=0,
                    center='com', center_options=dict(axes=1),
                    transform_options=dict(dr=0.5)).transform

f, (ax0, ax1, ax2) = plt.subplots(1, 3)

rows, cols = Tf.shape
r2 = rows//2
c2 = cols//2

slicepos = 120
slicewidth = 20

orig_prof = flame[slicepos-slicewidth:slicepos+slicewidth, c2:-1].sum(axis=0)
profile = Tf[slicepos-slicewidth:slicepos+slicewidth, c2+1:].sum(axis=0)


# plotting ---------------
ax0.imshow(flame)
ax0.set_ylabel("row pixels")
ax0.set_xlabel("col pixels")

ax1.imshow(Tf, vmin=0, extent=[-c2, c2, rows, 0])
ax1.set_ylabel("row pixels")
ax1.set_xlabel("radial (pixels)")

ax1.plot((-c2, c2), (slicepos, slicepos), color='y')

radial = np.arange(0, c2)
ax2.plot(radial, profile/profile.max())  
ax2.plot(radial, orig_prof[:-1]/orig_prof.max())

ax2.set_title("slice row = {}".format(slicepos), fontsize="smaller")
ax2.set_xlabel("radial (pixels)")
ax2.set_xticks([0, 10, 20, 30])

f.subplots_adjust(wspace=0.5)
plt.savefig("flameplot.png", dpi=75)
plt.show()
```

Note, I have added an additional parameter `axes` to `abel.tools.center_image()` and `abel.tools.set_center()` in order to **not** centre the image in the `axis=0` (row or y) direction. @DanHickstein I will open a PR for this change.

**Comment by Seonggun** [comment] 2017-03-03 08:06
Hi @stggh , Thanks, 

I deleted these images, how could you still have images? Strange. Since everything is on public, I deleted images.  

Images have been reconstructed.

**Comment by Seonggun** [comment] 2017-03-03 08:59
@DanHickstein , around 200 images with 318*100 for each case. Fourier method took over one hour to process images, but three points only takes a few minutes.

**Comment by DanHickstein** [comment] 2017-03-03 15:07
@Seonggun, at the core, three-point is using `np.tensordor()` to complete the transform. This function is actually completed using whatever math library numpy is linked against. You can check this by using `numpy.show_config()`. Mine looks like this:
```
lapack_opt_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
...
```

You may see a further speedup by using intel's MKL math library. (Apple's "Accelerate framework" is also fast.) If you are using a recent version of [Anaconda Python](https://www.continuum.io/downloads), then you are probably already using MKL. If not, you might consider switching to Anaconda.

**Comment by stggh** [comment] 2017-03-03 20:53
@Seonggun 
> I deleted these images, how could you still have images? 

Nothing nefarious, these comments are received as email.
