### ISSUE TITLE
Add comprehensive documentation

### ISSUE THREAD

**Issue by rth** [PyAbel/PyAbel#25] opened 2015-11-21 11:46 UTC
Some mechanism for including documentation with sphinx for the PyAbel module should be added.

One possibility is to use put in a separate repository on e.g. `PyAbel.github.io` . Alternatively it is possible to put it in the same repository and use `https://htmlpreview.github.io/?link_to_the_html_files.html`  as it is done for the [pyinstaller documentation](https://htmlpreview.github.io/?https://github.com/pyinstaller/pyinstaller/blob/develop/doc/Manual.html).  Not sure what are the drawbacks/advantages of each method.

**Comment by DanHickstein** [comment] 2015-11-21 17:52
Yes, I was thinking that it would be great to add some nice documentation. Also not sure the best way to do this. The pyinstaller page that you linked looks useful but a little bit ugly. Maybe we could include a brief introduction and overview information (with some nice images) on the PyAbel.github.io page, and then link to the sphinx generated documentation...

**Comment by rth** [comment] 2015-11-23 23:32
I agree that would be nice. I'm not so keen on the the Pyinstaller docs myself; I can work on the sphinx generated documentation if you want. As to the overview page, I'm not sure what would be the best layout/template for it  nor where it can be hosted, but it sound like a good idea.!

**Comment by DanHickstein** [comment] 2016-01-07 18:14
I think that there are two important aspects to the documentation. One is that we should have a way to get the docstrings nicely formatted on a webpage, as is the standard for Numpy, Scipy, and other Python modules. We don't really know how to do this yet, but the docstrings that are in the code are more-or-less okay.

A second important aspect is to provide additional information about the transforms, such as background information, advantages of the transform, relevant equations, deviations from papers (i.e., we correct typos), and general user advice. I think that the wiki provided by GitHhub is a quick and easy place to provide this information, using that standard Markdown syntax that we are accustomed to. So, I would say that we should start including the PyAbel documentation using the wiki: https://github.com/PyAbel/PyAbel/wiki

Each transform method should have it's own page, and there can also be a page for general information about abel transforms.

What does the team think about this? 

@rth @DhrubajyotiDas @stggh

**Comment by stggh** [comment] 2016-01-07 23:30
Looks good. 

Perhaps, with links for  `BASEX`  etc in the home page summary, to the relevant wiki, as per the right-side 'pages' navigation box, for easy access, and for those  that do not notice the right-side navigation box.

**Comment by DhrubajyotiDas** [comment] 2016-01-08 00:24
Good idea @stggh. I've added links to the individual sections from the home page summary and fleshed out the `three_point` section.

**Comment by DanHickstein** [comment] 2016-01-08 02:46
Nice work @DhrubajyotiDas! The wiki entry for the three-point transform looks beautiful!

**Comment by DanHickstein** [comment] 2016-01-13 15:51
A co-worker of mine showed me his github project, complete with [some documentation](http://pynlo.readthedocs.org/en/latest/package/pulse.html) of readthedocs.org. The documentation looked nice, and he said that it was pretty easy to generate using numpy-style docstrings, which are also very readable in the .py file. The numpy-style docstrings also support equations, which is great.

So, we should probably start writing out docstrings to conform to the numpy style: 

http://shimizukawa-sphinx.readthedocs.org/en/latest/ext/example_numpy.html

I think this is the guide about how to set up the sphinx-napolean aspect: 
http://sphinxcontrib-napoleon.readthedocs.org/en/latest/index.html

**Comment by DanHickstein** [comment] 2016-02-09 16:03
So, shouldn't the readthedocs.org page be working now? I'm not sure why it's still broken...
http://pyabel.readthedocs.org/en/latest/

**Comment by DanHickstein** [comment] 2016-02-09 16:08
Oh, whoops, I just needed to press the "Build" button on readthedocs.org. That was easy :)

**Comment by DanHickstein** [comment] 2016-02-18 16:34
Before we can close this issue (and get Version 0.7 out the door), one goal should be that we can build the documentation (go to /doc and type `make html`) without warnings and errors. Currently there are a lot of these.

**Comment by DhrubajyotiDas** [comment] 2016-02-18 17:06
I'm getting the following error when I try `make html` in /doc (Sorry, first time doing this...)

```
Dhrubajyoti Das@DhrubajyotiDas /cygdrive/e/My Documents/PyAbel/doc
$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.2.3
loading pickled environment... not yet created

Exception occurred:
  File "C:\Anaconda\lib\site-packages\sphinx\util\__init__.py", line 94, in get_matching_docs
    suffixpattern = '*' + suffix
TypeError: cannot concatenate 'str' and 'list' objects
The full traceback has been saved in c:\cygwin\tmp\sphinx-err-14f2bn.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
Makefile:55: recipe for target 'html' failed
make: *** [html] Error 1
```

**Comment by DanHickstein** [comment] 2016-02-18 17:23
Yeah, it took us all a while to get it to work as well. :)
I'm not sure exactly what is going wrong there, but do you have recommark and the sphinx_rtd_theme installed?
https://github.com/PyAbel/PyAbel/blob/master/CONTRIBUTING.md#documentation

**Comment by DhrubajyotiDas** [comment] 2016-02-18 17:43
`sphinx_rtd_theme` was the missing link. Thanks! 

```
Build finished. The HTML pages are in _build/html.
```
I'll go through the gazillion warnings and errors and see what I can fix.

**Comment by stggh** [comment] 2016-02-18 21:48
I believe I have all the sphinx programs installed, and recommonmark. The error, below, is also generated on my old PC, which did, once, run the doc generation.

```python
[etalon:.+/VMI/PyAbel/doc]$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.2.3
loading pickled environment... not yet created

Exception occurred:
  File "/usr/lib/python2.7/dist-packages/sphinx/util/__init__.py", line 94, in get_matching_docs
    suffixpattern = '*' + suffix
TypeError: cannot concatenate 'str' and 'list' objects
The full traceback has been saved in /tmp/sphinx-err-afuHLr.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
Makefile:55: recipe for target 'html' failed
make: *** [html] Error 1
```
The error file:
```python
# Sphinx version: 1.2.3
# Python version: 2.7.10
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 145, in __init__
    self._init_env(freshenv)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 191, in _init_env
    return self._init_env(freshenv=True)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 173, in _init_env
    self.env.find_files(self.config)
  File "/usr/lib/python2.7/dist-packages/sphinx/environment.py", line 350, in find_files
    self.srcdir, config.source_suffix, exclude_matchers=matchers))
  File "/usr/lib/python2.7/dist-packages/sphinx/util/__init__.py", line 94, in get_matching_docs
    suffixpattern = '*' + suffix
TypeError: cannot concatenate 'str' and 'list' objects
```

**Comment by DanHickstein** [comment] 2016-02-19 02:12
@stggh, are you sure that you have the `sphinx_rtd_theme` installed? That seemed to fix a similar error for @DhrubajyotiDas.

**Comment by stggh** [comment] 2016-02-19 03:00
Yes.
```python
[etalon:.+/VMI/PyAbel/doc]$ sudo apt-get install sphinx*
  :
sphinxtrain-dev is already the newest version.
0 to upgrade, 0 to newly install, 0 to remove and 14 not to upgrade.

[etalon:.+/VMI/PyAbel/doc]$ sudo apt-get install python-sphinx*
  :
python-sphinxcontrib.youtube is already the newest version.
0 to upgrade, 0 to newly install, 0 to remove and 14 not to upgrade.

[etalon:.+/VMI/PyAbel/doc]$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.2.3
loading pickled environment... not yet created

Exception occurred:
  File "/usr/lib/python2.7/dist-packages/sphinx/util/__init__.py", line 94, in get_matching_docs
    suffixpattern = '*' + suffix
TypeError: cannot concatenate 'str' and 'list' objects

```
I will play on my Mac at home to see whether the issue is resolved.

**Comment by DhrubajyotiDas** [comment] 2016-02-19 03:09
@stggh Just to make sure this isn't the issue, could you try

```
$ pip install sphinx_rtd_theme
```

[from here](https://pypi.python.org/pypi/sphinx_rtd_theme)

**Comment by stggh** [comment] 2016-02-19 03:25
Yes, that was done:
```python
[etalon:.+/VMI/PyAbel/doc]$ sudo pip install sphinx_rtd_theme
Requirement already satisfied (use --upgrade to upgrade): sphinx-rtd-theme in /usr/lib/python2.7/dist-packages
Cleaning up...
```

I had not made the changes to `conf.py`:
```python
In your conf.py file:

import sphinx_rtd_theme

html_theme = "sphinx_rtd_theme"

html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
```

The changes made no difference.

**Comment by stggh** [comment] 2016-02-19 20:09
make html works fine on my Mac, so there must be some package(s) missing on my Linux system. I will investigate further.

**Comment by DanHickstein** [comment] 2016-02-23 23:58
Maybe on Linux pip and apt-get are installing to the wrong python distribution? Are you abel to `import sphinx` in python?

**Comment by stggh** [comment] 2016-02-24 00:01
```python
[etalon:.+/stg121/VMI/Doc]$ ipython
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
Type "copyright", "credits" or "license" for more information.

IPython 2.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import sphinx

In [2]: sphinx.
sphinx.build_main    sphinx.package_dir   sphinx.version_info
sphinx.main          sphinx.path          
sphinx.make_main     sphinx.sys   
```

**Comment by DanHickstein** [comment] 2016-02-24 00:04
and that's the same /usr/lib/python that the makefile is trying to use?

**Comment by stggh** [comment] 2016-02-24 00:08
```python
[etalon:.+/stg121/VMI/Doc]$ which python
/usr/bin/python
[etalon:.+/stg121/VMI/Doc]$ /usr/bin/python --version
Python 2.7.10
```

**Comment by DanHickstein** [comment] 2016-02-24 00:10
Weird...

**Comment by DanHickstein** [comment] 2016-03-03 08:59
Docs are here!! 

At long last, closing this (issue 25!).

**Closed by DanHickstein** 2016-03-03 08:59 UTC
Labels: @high, doc
